### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'deal' - Closing Orders - orders.py

### ISSUE THREAD

**Issue by tHeStRyNg** [tHeStRyNg/ai_mt5_python#2]
```
[INFO]   ('127.0.0.1', 61021) CONNECTED
{'data': [1.06858, 1.06858, 1.06858, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 49.22836, 49.22836, 56.27954, 51.43508, 53.26179, 55.07817, 63.06667, 61.7798, 57.67126, 56.2144, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0, -1e-05, 1e-05, 1e-05, 0.0, 0.0, 0.0, -1e-05, -1e-05, -1e-05, -2e-05, -2e-05, 0.0, 0.0], 'macd': [1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0], 'signal': [1e-05, 1e-05, 0.0, 0 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0], 'signal': [1e-05, 1e-05, 0.0, 0.0, 0.0, -1e-05, -1e-05, -1e-05, -2e-05]}
[INFO]  ORDERS RUNNING
{'data': [1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 53.89403, 53.89403, 53.89403, 49.22836, 56.27954, 51.43508, 53.26179, 55.07817, 63.06667, 61.7798, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0, 0.0, -1e-05, -1e-05, -1e-05, 0.0, 0.0], 'macd': [1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05], 'signal': [1e-05, 1e-05, 1e 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05], 'signal': [1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0, 0.0, -1e-05, -1e-05]}
{'data': [1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06859, 1.06859, 1.06859, 55.12742, 55.12742, 50.31882, 53.89403, 53.89403, 49.22836, 56.27954, 51.43508, 53.26179, 55.07817, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0, 0.0, -1e-05, 0.0, 1.0], 'macd': [1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05], 'signal': [1e-05, 1e-05, 1, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05], 'signal': [1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0, 0.0]}
{'data': [1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 53.83929, 53.83929, 53.83929, 60.59927, 59.00611, 61.30802, 61.30802, 56.9653, 51.95835, 58.25165, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05, 1e-05, 2e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 0.0, 0.0], 'macd': [2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05], 'signal': [2e-05, 2e-0e-05, 2e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05], 'signal': [2e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05]}
{'data': [1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 55.7274, 55.7274, 53.96361, 50.28535, 48.37009, 42.16305, 45.55326, 43.44183, 43.44183, 56.71723, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1e-05, 1e-05, 0.0, 0.0, 0.0, 0.0, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 2e-05, 1.0, 1.0], 'macd': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
1e-05], 'signal': [0.0, 0.0, 0.0, 0.0, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05]}
{'data': [1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06858, 1.06858, 1.06858, 1.06858, 1.06858, 60.68764, 59.12951, 59.12951, 65.88424, 64.63373, 66.91117, 69.1745, 68.17488, 74.94513, 66.77499, 3e-05, 4e-05, 4e-05, 4e-05, 4e-05, 4e-05, 4e-05, 3e-05, 3e-05, 1e-05, 4e-05, 3e-05, 3e-05, 3e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05, 0.0, 1.0, 0.0], 'macd': [3e-05, 4e-05, 4e-05, 4e-05, 4e-05, 4e-05, 4e-05, 3e-05, 3e-05], 'signal': [4e-05, 3e-05, 3e-05, 3e-05, 2e-05, 2e-05, 2e-05, 1e-05, 1e-05]}
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06868 with deviation=20 points
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06866 with deviation=20 points
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06862 with deviation=20 points
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06864 with deviation=20 points
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06863 with deviation=20 points
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06865 with deviation=20 points
{'data': [1.0686, 1.0686, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 1.06859, 61.26754, 59.73302, 52.78511, 57.38202, 53.63243, 49.50732, 49.50732, 49.50732, 45.63486, 58.0335, 2e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 2e-05, 2e-05, 3e-05, 1e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 3e-05, 3e-05, 3e-05, 3e-05, 1.0, 1.0], 'macd': [2e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 1e-05, 2e-05, 2e-05], 'signal': [1e-05, 2e-05, 2e-05, 2e-05, 2e-05, 2e-05, 3e-05, 3e-05, 3e-05]}
[Thread - orders] 1. order_send(): by EURUSD 1.0 lots at 1.06864 with deviation=20 points
[Thread - orders] Failed operation: retcode=10016
Exception in thread Thread-2 (thread_orders_AI):
Traceback (most recent call last):
  File "C:\Users\Markt\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Markt\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Markt\Desktop\code\ai_mt5_python\bot\orders.py", line 113, in thread_orders_AI
    close_position(trading_data["market"], trading_data["lotage"], result)
  File "C:\Users\Markt\Desktop\code\ai_mt5_python\bot\orders.py", line 20, in close_position
    deal = mt5.history_deals_get(ticket=result.deal)[0]
                                        ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'deal'
```

**Comment by iaananth** [comment]
How did fix? I received the same problem.
